### ISSUE TITLE
A4MKII individual synth tracks not stereo?

### ISSUE THREAD

**Issue by serratedserenade** [dagargo/overwitch#23]
So I just noticed that the individual tracks out as mono instead of stereo for Overwitch, so this renders the internal panning to not work. It does work when I plug into the individual out on the device.

**Comment by dagargo** [comment]
I'm not sure if this is an issue. Let me explain myself.

The Digitakt has the same problem, so I suspect that it is by design. After all, Overbridge sends the individual outputs and panning makes not much sense. Take a look at [this topic](https://www.elektronauts.com/t/overbridge-digitakt-and-track-panning) about this issue.

With regards to the A4MKII, I suspect it's the same issue but I don't know why as the 4 tracks are stereo opossed to the 8 individual mono outs of the Digitakt.

OTOH, Overwitch provides audio and MIDI but I'm not sure if the panning information goes by default through the MIDI port or if it travels through the Overbridge protocol, which is not implemented.

**Comment by serratedserenade** [comment]
Heya, just saw your comment. Maybe I'll have to check on a Windows laptop, but I assumed that it should support it. I noticed that Overwitch was able to see that the Digitone has 2 channels per track so I thought it would be the same for A4.

**Comment by dagargo** [comment]
This was a bad assumption by me. I saw the signal path chart on the manual and I got confused.

> as the 4 tracks are stereo 

They are mono. A4MKII is a 6 input (main stereo input and an input per track), 8 output (main stereo output, an output per track and the stereo input) Overbridge device.

Panning can not have any effect on a mono channel unless you're mixing down to stereo, which you're supposed to do with your DAW. I guess this is the reason it doesn't work.

OTOH, Digitione is a 2 input 12 output (main stereo output, stereo input and 4 stereo pairs) Overbridge device. That's why it works on the Digitone.

This is by design and we can't do anything about it. But you can still try to configure your DAW to listen to the pan control in the A4MKII tracks and send it to the pan control in the mixer tracks.
