### ISSUE TITLE
Cannot build on Debian Bullseye

### ISSUE THREAD

**Issue by ThaYke** [dagargo/overwitch#3]
Hi there,
very interesting project. Unfortunately I'm not able to build it on my machine. When I follow the instructions all seems to work well until the `make`. Then it throws many (linking?-)errors at me and fails ultimately at:
```
/usr/bin/ld: /build/overwitch/src/overbridge.c:560: undefined reference to `jack_ringbuffer_free'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:343: overwitch] Fehler 1
```
This is on Debian testing with all dependencies installed.

As I'm by no means a linux expert, any hint for me how to make this compile? Would love to try it out.

**Comment by dagargo** [comment]
Thanks for pointing this out.

I could replicate the issue on an Ubuntu 21.04 VM. I've checked a few things and the compiling options for the libraries were not set up properly. Fixed in f3cb4bcc7d5fbbfaf2e9c65ad4947276cc13e454.

If you don't mind, could you share what devices are you using Overwitch with? What are your thoughts about it? Is it working well for you? What's your setup? I haven't received much feedback yet so your opinion is really valuable.

TIA.

**Comment by ThaYke** [comment]
Thanks for your reply. As soon as I will have time I'll retry to compile and check basic functionality out. I'm panning to use it with my Digitakt & Bitwig on my Debian machine. Would be awesome to have separate outs in some way. :)

**Comment by ThaYke** [comment]
So, by now I did some fiddling around with an iRig Pro I/O as interface connected to my notebook running Debian Bullseye (CPU: Intel i7-8565U, 16GB RAM)  with Liquorix RT-kernel ( 5.10.0-17.1-liquorix-amd64).
Jack and Pulseaudio bridge running @ 3x128 buffersize, 48000Hz, 8ms latency, no audible xruns whatsoever until now.
Seems to work fine for me. Amazing project! Thanks a lot!

**Comment by dagargo** [comment]
Thanks for the information.

I'm glad that it works now.
